# The 0.5.x released libraries do not install the header files and libraries in
# their CMake setup. We need to use brotli as a library
{% set version = "0.6.0" %}

package:
  name: brotli
  version: {{ version }}

source:
  fn: brotli-{{ version }}.tar.gz
  url: https://github.com/google/brotli/archive/v{{ version }}.tar.gz
  sha256: 69cdbdf5709051dd086a2f020f5abf9e32519eafe0ad6be820c667c3a9c9ee0f

build:
  number: 0
  skip: true  # [win and (py36 or py27)]

  features:
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - toolchain
    - cmake
    - python  # [win]

test:
  requires:
    - python 3.4.*  # [win and py34]
    - python 3.5.*  # [win and py35]
  commands:
    - test -f $PREFIX/include/brotli/encode.h  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\bro.exe exit 1                   # [win]
    - if not exist %PREFIX%\\Library\\bin\\bro_static.exe exit 1            # [win]
    - if not exist %PREFIX%\\Library\\bin\\brotlicommon.dll exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\brotlidec.dll exit 1             # [win]
    - if not exist %PREFIX%\\Library\\bin\\brotlienc.dll exit 1             # [win]
    - if not exist %PREFIX%\\Library\\lib\\brotlicommon.lib exit 1          # [win]
    - if not exist %PREFIX%\\Library\\lib\\brotlicommon_static.lib exit 1   # [win]
    - if not exist %PREFIX%\\Library\\lib\\brotlidec.lib exit 1             # [win]
    - if not exist %PREFIX%\\Library\\lib\\brotlidec_static.lib exit 1      # [win]
    - if not exist %PREFIX%\\Library\\lib\\brotlienc.lib exit 1             # [win]
    - if not exist %PREFIX%\\Library\\lib\\brotlienc_static.lib exit 1      # [win]
    - if not exist %PREFIX%\\Library\\include\\brotli\\encode.h exit 1      # [win]

about:
  home: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: 'Brotli compression format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
