{% set version = "1.0.6" %}

package:
  name: brotli
  version: {{ version }}

source:
  fn: brotli-{{ version }}.tar.gz
  url: https://github.com/google/brotli/archive/v{{ version }}.tar.gz
  sha256: ce94b7f48af5e8f444c3949ca93201c1b4bb40da633db084e900133ce87848db

build:
  number: 1000
  skip: true  # [win and vc<14]


requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - brotli --help
    - test -f $PREFIX/lib/libbrotlienc$SHLIB_EXT     # [unix]
    - test -f $PREFIX/lib/libbrotlienc-static.a      # [unix]
    - test -f $PREFIX/lib/libbrotlidec$SHLIB_EXT     # [unix]
    - test -f $PREFIX/lib/libbrotlidec-static.a      # [unix]
    - test -f $PREFIX/lib/libbrotlicommon$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/libbrotlicommon-static.a   # [unix]
    - test -f $PREFIX/include/brotli/encode.h        # [unix]
    - if not exist %LIBRARY_BIN%\\brotli.exe exit 1               # [win]
    - if not exist %LIBRARY_BIN%\\brotlicommon.dll exit 1         # [win]
    - if not exist %LIBRARY_BIN%\\brotlidec.dll exit 1            # [win]
    - if not exist %LIBRARY_BIN%\\brotlienc.dll exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\brotlicommon.lib exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\brotlicommon-static.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\brotlidec.lib exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\brotlidec-static.lib exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\brotlienc.lib exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\brotlienc-static.lib exit 1     # [win]
    - if not exist %LIBRARY_INC%\\brotli\\encode.h exit 1         # [win]

about:
  home: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: 'Brotli compression format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - CJ-Wright
