# The 0.5.x released libraries do not install the header files and libraries in
# their CMake setup. We need to use brotli as a library
{% set version = "0.6.pre" %}
{% set commit = "5db62dcc9d386579609540cdf8869e95ad334bbd" %}

package:
  name: brotli
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/google/brotli/archive/{{ commit }}.tar.gz
  sha256: fcc70cacaf3833e22fad242c0e4f44ab0ae4e570ebdb954f985182f4ce1bff74

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -f $PREFIX/include/brotli/encode.h  # [unix]

about:
  home: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: 'Brotli compression format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
