appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: Jlq+STxqohgSVYRmWMNaIf3dpnIp2D7R5Nc+vZsJqrGip2sWReHwcHCx3WGVmXBzuPxY77lze+FMNeTxA8cZn/UNZXFTU0IwR1oYTkUI6HqtNs8uwtFHDFgFaXSlx9yx/Mec9BUDaEEYybRxIK667HawRiXYv4P59luS6hOgBpfG0PyVORmxpWsL1vCZQGA1Z7MGyPD6NExFU+x5DW2OsYOpEvh73nNdDjiCghGn0J0GHQAA7sHqdvTHG3UJlnZQ4fmEftYCGHcqr7nCJ9oZyNi1Cy9s8GHRlZEggMoqo3qO9s/XNUoZUSTcuxAlkAHygLY52zsBVuiLXUmqxQuVrPmLgePQ7SeWyOcoajfNZgQBAkBWOaFSLsWPFHI9kJiYD81qmP2zLSiEQyIXO7KDVXEZTrXBrIqFoCqAW4lNC+1CEvFzoyGGRF0lEjvqv5icxbOHX6xI2dt9jSrCZeiGm+rRMn2s8WDBhUK99VjVgeZgssmXcTuFSWTzrPEGu1ozEPlG348ikx4EcMK3ONOzxZc5bn8P5PT9Df/+gxsoU31tNkBFFdPRPkrFCijBcKxGa0PI3A4FsXMno8D8NOxWBHlIBEOvq1VzQtTkX79zZGWfTjLUE58E060D3TbQ9uoq/J++sT+lrZT753LeZGb9/jTfSY6QS1mFqLr2Yj8Idz0=}
